#!/usr/bin/env bash

set -e

root=$(git rev-parse --show-toplevel)
pkg=github.com/collinvandyck/gpterm/cmd/gpterm
args="--log ${root}/gpterm.log --request-log ${root}/request.log --pprof=true"

export CGO_ENABLED=0
exec go run $pkg $args $@
