// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package query

import (
	"context"
)

const getAPIKey = `-- name: GetAPIKey :one
SELECT value FROM credential
WHERE name='api_key' LIMIT 1
`

func (q *Queries) GetAPIKey(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO credential (name, value) values ('api_key', ?)
`

func (q *Queries) InsertAPIKey(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, insertAPIKey, value)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE credential set value=? where name='api_key'
`

func (q *Queries) UpdateAPIKey(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, updateAPIKey, value)
	return err
}
